name: Check branch

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test
      - name: Store build results
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
